---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - metrics.timmelmann.com
  resources:
  - metricsoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.timmelmann.com
  resources:
  - metricsoperators/finalizers
  verbs:
  - update
- apiGroups:
  - metrics.timmelmann.com
  resources:
  - metricsoperators/status
  verbs:
  - get
  - patch
  - update
