apiVersion: metrics.timmelmann.com/v1
kind: MetricsOperator
metadata:
  labels:
    app.kubernetes.io/name: timmelmann
    app.kubernetes.io/managed-by: kustomize
  name: metricsoperator
  namespace: metrics-system
spec:
  collector:
    endpointUrl: "http://prometheus-server.monitoring.svc.cluster.local:80"
    metricsWindow: "60m"
    step: "1m"
    customQuery:
      query: "istio_requests_total"
      labels:
        - destination_app
        - source_app
        - reporter

  # Analyzer configuration
  analyzer:
    endpointUrl: "http://graph-based-predictor-service.metrics-operator.svc.cluster.local:80"

  # Pusher configuration
  pusher:
    endpointUrl: "http://prometheus-prometheus-pushgateway.monitoring.svc.cluster.local:9091"
    metricName: "predicted_request_count_webshop"
    jobName: "metrics_collection"

  # Interval in seconds between metric collections
  interval: "1m"
  maxRetries: 3

  # List of applications to monitor
  applications:
    namespace: "webshop"
    services:
      - name: "adservice"
        deploymentName: "adservice"
        minReplicas: 1
        maxReplicas: 10
        targetValue: 10000
        targetType: "Value"
      - name: "cartservice"
        deploymentName: "cartservice"
        minReplicas: 1
        maxReplicas: 10
        targetValue: 10000
        targetType: "Value"
      - name: "checkoutservice"
        deploymentName: "checkoutservice"
        minReplicas: 1
        maxReplicas: 10
        targetValue: 10000
        targetType: "Value"
      - name: "currencyservice"
        deploymentName: "currencyservice"
        minReplicas: 1
        maxReplicas: 10
        targetValue: 10000
        targetType: "Value"
      - name: "emailservice"
        deploymentName: "emailservice"
        minReplicas: 1
        maxReplicas: 10
        targetValue: 10000
        targetType: "Value"
      - name: "frontend"
        deploymentName: "frontend"
        minReplicas: 1
        maxReplicas: 10
        targetValue: 10000
        targetType: "Value"
      - name: "paymentservice"
        deploymentName: "paymentservice"
        minReplicas: 1
        maxReplicas: 10
        targetValue: 10000
        targetType: "Value"
      - name: "productcatalogservice"
        deploymentName: "productcatalogservice"
        minReplicas: 1
        maxReplicas: 10
        targetValue: 10000
        targetType: "Value"
      - name: "recommendationservice"
        deploymentName: "recommendationservice"
        minReplicas: 1
        maxReplicas: 10
        targetValue: 10000
        targetType: "Value"
      - name: "shippingservice"
        deploymentName: "shippingservice"
        minReplicas: 1
        maxReplicas: 10
        targetValue: 10000
        targetType: "Value"
